[ballerinax.wso2.controlplane]
icpServicePort = 9265

[ballerinax.wso2.controlplane.dashboard]
url = "https://localhost:9743/dashboard/api"
heartbeatInterval = 10
groupId = "Ripplit"
mgtApiUrl ="https://host.docker.internal:9265/management/"
nodeId = "Sentiment AI Node"
