version: "2.14.0"

services:
  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    network_mode: "host"

  sentiment-api:
    container_name: sentiment-api
    build:
      context: sentiment_api
      dockerfile: Dockerfile
    ports:
      - 9098:9098
    depends_on:
      - icp
    network_mode: "host"

  mysql:
    image: "mysql:8-oracle"
    container_name: mysql
    ports:
      - 3306:3306
    network_mode: "host"
    environment:
      - MYSQL_ROOT_PASSWORD=dummypassword
      - MYSQL_DATABASE=ripplit_db
      - MYSQL_USER=dummyuser
      - MYSQL_PASSWORD=dummypassword
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - "./db-setup/init.sql:/docker-entrypoint-initdb.d/1.sql"

  jaeger:
    image: 'jaegertracing/opentelemetry-all-in-one'
    container_name: jaeger
    ports:
      - 13133:13133
      - 16686:16686
      - 55680:55680
    network_mode: "host"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 19090:9090
    volumes: 
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    network_mode: "host"
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    network_mode: "host"
    depends_on:
      - prometheus
    volumes: 
      - ./grafana/provisioning/:/etc/grafana/provisioning/

  icp:
    image: 'wso2/wso2-integration-control-plane'
    container_name: icp
    network_mode: "host"
    ports:
      - 9743:9743
      - 9264:9264
